openapi: 3.0.0
servers:
  - url: 'http://localhost:8089/api'
info:
  description: Create your own film libraries
  version: 1.0.0
  title: FilmLibraryAPI
  contact: 
    email: 
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
tags:
  - name: films
    description: Films we can find in Netflix
  - name: library
    description: A place to save the films you love or you want to watch
paths:
  /films:
    get:
      tags:
        - films
      summary: Get all the films available
      description: You will get every film you are able to watch from Netflix
      operationId: getFilms
      parameters:
        - name: sort
          in: query
          description: Order resulting films by different possibilities
          required: false
          schema:
            type: string
            enum:
              - score
              - '-score'
              - date
              - '-date'
              - title
              - '-title'
              - runtime
              - '-runtime'
        - name: offset
          in: query
          description: Offset of the results 
          required: false
          schema:
            type: integer
            format: int32
            minimun: 0
        - name: limit
          in: query
          description:  Maximum number of results
          required: false
          schema:
            type: integer
            format: int32
            minimum: 0
        - name: score
          in: query
          description: Range of score of the results 
          schema:
            type: string
        - name: title
          in: query
          description: Filter by matching title 
          schema:
            type: string
        - name: genre
          in: query
          description: Filter by matching genre 
          schema:
            type: string
        - name: runtime
          in: query
          description: Filter by matching runtime 
          schema:
            type: Integer
            format: int32
            minimun: 0
        - name: premiere
          in: query
          description: Filter by matching premiere date, format ('dd-MM-YYYY')
          schema:
            type: string
        - name: language
          in: query
          description: Filter by matching language 
          schema:
            type: string
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - title
                  properties:
                    id:
                      type: string
                    title:
                      type: string
                    genre:
                      type: string
                    premiere:
                      type: string
                    runtime:
                      type: integer
                    score: 
                      type: double
                    language:
                      type: array
                      items:
                        type: string
                  example:
                    id: f500
                    title: 'El Camino: A Breaking Bad Movie'
                    genre: 'Crime drama'
                    premiere: '11-10-2019'
                    runtime: 121
                    score: 7.3
                    language: ['English']
        '400':
          description: Bad request
    post:
      tags:
        - films
      summary: Upload film information
      description: You can upload film information not in our database
      operationId: createFilm
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - title
                - genre
                - premiere
                - runtime
                - score
                - language
              properties:
                id:
                  type: string
                title:
                  type: string
                genre:
                  type: string
                premiere:
                  type: string
                runtime:
                  type: integer
                score: 
                  type: double
                language:
                  type: array
                  items:
                    type: string
              example:
                title: 'El Camino: A Breaking Bad Movie'
                genre: 'Crime drama'
                premiere: '11-10-2019'
                runtime: 121
                score: 7.3
                language: ['English']
        description: Film information to upload
        required: true
      responses:
        '201':
          description: Film information uploaded
          content:
            application/json:
              schema:
                type: object
                required:
                  - title
                  - genre
                  - premiere
                  - runtime
                  - score
                  - language
              properties:
                id:
                  type: string
                title:
                  type: string
                genre:
                  type: string
                premiere:
                  type: string
                runtime:
                  type: integer
                score: 
                  type: double
                language:
                  type: array
                  items:
                    type: string
              example:
                id: f500
                title: 'El Camino: A Breaking Bad Movie'
                genre: 'Crime drama'
                premiere: '11-10-2019'
                runtime: 121
                score: 7.3
                language: ['English']
        '400':
          description: Bad request
  '/films/{id}':
    delete:
      tags:
        - films
      summary: Delete a film information
      description: Delete any film information from the database
      operationId: deleteFilm
      parameters:
        - name: id
          in: path
          description: Id of the film
          required: true
          schema:
            type: string
      responses:
        '204':
          description: film deleted
        '404':
          description: film not found
  /libraries:
    get:
      tags:
        - libraries
      summary: Get all libraries
      description: Get all libraries every user has created
      operationId: getLibraries
      parameters:
        - name: order
          in: query
          description: Order results by name
          required: false
          schema:
            type: string
            enum:
              - name
              - '-name'
        - name: isEmpty
          in: query
          description: Filter playlists with no songs
          required: false
          schema:
            type: boolean
        - name: name
          in: query
          description: Filter playlists by name
          required: false
          schema:
            type: string
      responses:
        '200':
          description: Search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - name
                  properties:
                    id:
                      type: string
                    name:
                      type: string
                    description:
                      type: string
                    songs:
                      type: array
                      items:
                        type: object
                        required:
                          - title
                        properties:
                          id:
                            type: string
                          title:
                            type: string
                          artist:
                            type: string
                          album:
                            type: string
                          year:
                            type: string
                  example:
                    id: p5
                    name: Favourites
                    description: My favourite songs
                    songs:
                      - id: s1
                        title: Rolling in the Deep
                        artist: Adele
                        album: '21'
                        year: '2011'
        '400':
          description: Bad request
    put:
      tags:
        - lists
      summary: Update a playlist
      description: Update a playlist
      operationId: updatePlaylist
      requestBody:
        content:
          application/json:
            schema:
              required:
                - name
              properties:
                id:
                  type: string
                name:
                  type: string
                description:
                  type: string
                songs:
                  type: array
                  items:
                    type: object
                    required:
                      - title
                    properties:
                      id:
                        type: string
                      title:
                        type: string
                      artist:
                        type: string
                      album:
                        type: string
                      year:
                        type: string
              example:
                id: p5
                name: Favourites
                description: My favourite songs
                songs:
                  - id: s1
                    title: Rolling in the Deep
                    artist: Adele
                    album: '21'
                    year: '2011'
        description: Playlist to update
      responses:
        '204':
          description: Playlist updated
        '400':
          description: Bad request
        '404':
          description: Playlist not found
  '/lists/{id}':
    get:
      tags:
        - lists
      summary: Get a playlist
      description: Get a playlist
      operationId: getPlaylist
      parameters:
        - name: id
          in: path
          description: Id of the playlist
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Playlist found
          content:
            application/json:
              schema:
                required:
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  songs:
                    type: array
                    items:
                      type: object
                      required:
                        - title
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        artist:
                          type: string
                        album:
                          type: string
                        year:
                          type: string
                example:
                  id: p5
                  name: Favourites
                  description: My favourite songs
                  songs:
                    - id: s1
                      title: Rolling in the Deep
                      artist: Adele
                      album: '21'
                      year: '2011'
        '404':
          description: Playlist not found
  '/lists/{playlistId}/{songId}':
    post:
      tags:
        - lists
      summary: Add song to playlist
      description: Add song to playlist
      operationId: addSongToPlaylist
      requestBody:
        content:
          text/plain:
            schema:
              type: string
      parameters:
        - name: playlistId
          in: path
          description: Id of the playlist
          required: true
          schema:
            type: string
        - name: songId
          in: path
          description: Id of the song
          required: true
          schema:
            type: string
      responses:
        '201':
          description: Song added to playlist
          content:
            application/json:
              schema:
                required:
                  - name
                properties:
                  id:
                    type: string
                  name:
                    type: string
                  description:
                    type: string
                  songs:
                    type: array
                    items:
                      type: object
                      required:
                        - title
                      properties:
                        id:
                          type: string
                        title:
                          type: string
                        artist:
                          type: string
                        album:
                          type: string
                        year:
                          type: string
                example:
                  id: p5
                  name: Favourites
                  description: My favourite songs
                  songs:
                    - id: s1
                      title: Rolling in the Deep
                      artist: Adele
                      album: '21'
                      year: '2011'
        '400':
          description: Bad request
        '404':
          description: Playlist or song not found
    delete:
      tags:
        - lists
      summary: Delete song from playlist
      description: Delete song from playlist
      operationId: deleteSongFromPlayist
      parameters:
        - name: playlistId
          in: path
          description: Id of the playlist
          required: true
          schema:
            type: string
        - name: songId
          in: path
          description: Id of the song
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Song deleted from playlist
        '404':
          description: Playlist or song not found